# -*- coding: utf-8 -*-
"""ecec147_finalvisualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U4NPCHcEXPyB_e6dCB-yYO451tCZ1Zma
"""

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/ECE_C147/emg2qwerty-main

!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard

# Commented out IPython magic to ensure Python compatibility.
#BASE_TRAIN - VAL CER = 20.0044, LOSS = 0.6945, 1.5 hours
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-11/19-45-36"

# Commented out IPython magic to ensure Python compatibility.
#RNN_TRAIN - VAL CER = 19.5171, LOSS = 0.6383
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-12/07-13-34"

# Commented out IPython magic to ensure Python compatibility.
#Hybrid_TRAIN- VAL CER - 17.3239, LOSS - 0.5924
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/00-57-49"

# Commented out IPython magic to ensure Python compatibility.
#deep TRAIN - VAL CER - 98.56, LOSS - 104.379
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/03-32-27"

# Commented out IPython magic to ensure Python compatibility.
#deep TEST - CER 100
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/05-23-39/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

# Commented out IPython magic to ensure Python compatibility.
#Hybrid TEST - CER 18.3704
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/03-03-56/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

# Commented out IPython magic to ensure Python compatibility.
#RNN_TEST - CER 21.0071
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/03-18-18/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

# Commented out IPython magic to ensure Python compatibility.
#BASE_TEST - CER 22.471
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/03-24-37/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

"""# Experiment 2"""

# Commented out IPython magic to ensure Python compatibility.
#Hybrid 30 epoch TRAIN - VAL CER = 21.0456, LOSS = 0.6999
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/05-35-38"

# Commented out IPython magic to ensure Python compatibility.
#Hybrid 30 epoch TEST - CER = 22.6497
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/06-33-38/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

# Commented out IPython magic to ensure Python compatibility.
#14 sessions TRAIN - Val/CER = 23.7931, Loss = 0.7622
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/06-45-21"

# Commented out IPython magic to ensure Python compatibility.
#14 sessions TEST - Test/CER = 24.6164
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/17-08-57/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

# Commented out IPython magic to ensure Python compatibility.
#9 sessions TRAIN - Loss = 1.1808, Val/CER = 45.075
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/16-13-57"

# Commented out IPython magic to ensure Python compatibility.
#9 sessions TEST - Test/CER = 42.4033
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/17-12-49/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

# Commented out IPython magic to ensure Python compatibility.
#62.5 Hz TRAIN - Loss = 1.8883, Val/CER = 60.7490
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/21-12-56"

# Commented out IPython magic to ensure Python compatibility.
#62.5 Hs TEST - TEST/CER = 48.1521
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/22-54-16/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

# Commented out IPython magic to ensure Python compatibility.
#smart model- TRAIN = 0.6653, Val CER = 19.5815
#max_offset = 60, time masks = 2, time param = 25 freq maks = 2, freq param = 4

# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-13/23-36-51"

# Commented out IPython magic to ensure Python compatibility.
#smart model- TEST CER = 20.3588
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-14/00-36-59/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"

# Commented out IPython magic to ensure Python compatibility.
#smartmodel 2 - TRAIN loss = 0.6205, val/CER = 18.3897
#max_offset = 30, time masks = 1, time param = 12 freq maks = 1, freq param = 2
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-14/00-46-34"

# Commented out IPython magic to ensure Python compatibility.
#smartmodel 2 - TEST/CER = 19.9265
#max_offset = 30, time masks = 1, time param = 12 freq maks = 1, freq param = 2
# %tensorboard --logdir="/content/drive/MyDrive/ECE_C147/emg2qwerty-main/logs/2025-03-14/01-45-48/job0_decoder=ctc_greedy,train=False,user=single_user/lightning_logs"